import httplib
from user_list import *
import re
from xml.dom.minidom import Document


for egroup in egroup_user_list:
    users = egroup_user_list[egroup]
    users = re.sub(' +',' ',users)
    user_list = users.split(" ")
    print user_list
    for user in user_list:
        doc = Document()
        soap_envelope = doc.createElement("soap:Envelope")
        soap_envelope.setAttribute('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
        soap_envelope.setAttribute('xmlns:xsd','http://www.w3.org/2001/XMLSchema')
        soap_envelope.setAttribute('xmlns:soap','http://schemas.xmlsoap.org/soap/envelope/')
        soap_body = doc.createElement("soap:Body")
        add_egroup_mem_req =  doc.createElement("addEgroupMembersRequest")
        add_egroup_mem_req.setAttribute('xmlns','https://cra-ws.cern.ch/cra-ws/' )
        niceuserid = doc.createElement('p_niceUserid')
        niceuserid.appendChild(doc.createTextNode(nice_login))
        password = doc.createElement('p_password')
        password.appendChild(doc.createTextNode(nice_password))
        egroupname = doc.createElement('p_egroupName')
        egroupname.appendChild(doc.createTextNode(egroup))
        overwrite = doc.createElement('p_overwriteMembers')
        overwrite.appendChild(doc.createTextNode('False'))
        egroup_members = doc.createElement('p_members')
        member = doc.createElement('Member')
        member.setAttribute('xmlns','http://cra.web.cern.ch/cra/xml' )
        member_id = doc.createElement('ID')
        member_id.appendChild(doc.createTextNode(user))
        member_type = doc.createElement('Type')
        member_type.appendChild(doc.createTextNode('Account'))
        member_name = doc.createElement('Name')
        member_name.appendChild(doc.createTextNode(user))        
        member.appendChild(member_id)
        member.appendChild(member_type)
        member.appendChild(member_name)        
        egroup_members.appendChild(member)
        add_egroup_mem_req.appendChild(niceuserid)  
        add_egroup_mem_req.appendChild(password)
        add_egroup_mem_req.appendChild(egroupname)
        add_egroup_mem_req.appendChild(overwrite)
        add_egroup_mem_req.appendChild(egroup_members)        
        soap_body.appendChild(add_egroup_mem_req)
        soap_envelope.appendChild(soap_body)
        doc.appendChild(soap_envelope)
        soap_message = doc.toprettyxml(indent="",newl='')        
        webservice = httplib.HTTPSConnection('cra-ws.cern.ch', 443)
        webservice.putrequest("POST", "/cra-ws/CraEgroupsWebService HTTP/1.1")
        webservice.putheader("User-Agent", "Python post")
        webservice.putheader("Content-Length", "%d" % len(soap_message))
        webservice.putheader("Content-Type", "text/xml; charset=utf-8")
        webservice.putheader("SOAPAction", "\"https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/addEgroupMembers\"")
        webservice.endheaders()
        webservice.send(soap_message)        
        response = webservice.getresponse()
        print response.status, response.reason ,response.read()         
